/*SCHOOL 테이블 생성*/
CREATE TABLE SCHOOL (
    STUDENT_ID NUMBER NOT NULL
  , STUDENT_NAME VARCHAR(20) NOT NULL
  , SUBJECT VARCHAR(20)
  , SCORE NUMBER
  , CLASS VARCHAR(5)
  , CONSTRAINT STUDENT_PK PRIMARY KEY (STUDENT_ID)
);

/*SCHOOL 테이터 생성*/
INSERT INTO SCHOOL
(STUDENT_ID, STUDENT_NAME, SUBJECT, SCORE)
VALUES (001, '백종원', '국어', 85, '10');

INSERT INTO SCHOOL
(STUDENT_ID, STUDENT_NAME, SUBJECT, SCORE)
VALUES (002, '이나영', '국어', 80, '20');

INSERT INTO SCHOOL
(STUDENT_ID, STUDENT_NAME, SUBJECT, SCORE)
VALUES (003, '김하늘', '국어', 60, '10');

INSERT INTO SCHOOL
(STUDENT_ID, STUDENT_NAME, SUBJECT, SCORE)
VALUES (004, '아이유', '국어', 45, '20');

INSERT INTO SCHOOL
(STUDENT_ID, STUDENT_NAME, SUBJECT, SCORE)
VALUES (005, '윤종신', '국어', 75, '10');

INSERT INTO SCHOOL
(STUDENT_ID, STUDENT_NAME, SUBJECT, SCORE)
VALUES (006, '성시경', '국어', 55, '20');

INSERT INTO SCHOOL
(STUDENT_ID, STUDENT_NAME, SUBJECT, SCORE)
VALUES (007, '김혜원', '국어', 40, '10');

INSERT INTO SCHOOL
(STUDENT_ID, STUDENT_NAME, SUBJECT, SCORE)
VALUES (008, '강나래', '국어', 90, '20');

INSERT INTO SCHOOL
(STUDENT_ID, STUDENT_NAME, SUBJECT, SCORE)
VALUES (009, '김옥중', '국어', 83, '30');

INSERT INTO SCHOOL
(STUDENT_ID, STUDENT_NAME, SUBJECT, SCORE)
VALUES (010, '나영해', '국어', 90, '30');

INSERT INTO SCHOOL
(STUDENT_ID, STUDENT_NAME, SUBJECT, SCORE)
VALUES (011, '나얼', '국어', NULL, '30');
